const tourSteps = [
  {
    id: 'welcome',
    path: '/market',
    selector: null,
    titleKey: 'onboarding.tour.welcome.title',
    descKey: 'onboarding.tour.welcome.desc',
    placement: 'center',
    padding: 0,
  },
  {
    id: 'market-tabs',
    path: '/market',
    selector: '[data-tour="market-tabs"]',
    titleKey: 'onboarding.tour.marketTabs.title',
    descKey: 'onboarding.tour.marketTabs.desc',
    placement: 'bottom',
    padding: 10,
  },
  {
    id: 'market-rates',
    path: '/market',
    clickSelector: '[data-tour="market-rates-tab"]',
    selector: '[data-tour="market-rates-content"]',
    titleKey: 'onboarding.tour.marketRates.title',
    descKey: 'onboarding.tour.marketRates.desc',
    placement: 'top',
    padding: 10,
    slowLoad: true,
  },
  {
    id: 'market-macro',
    path: '/market',
    clickSelector: '[data-tour="market-macro-tab"]',
    closeSelector: '[data-tour="market-overview-tab"]',
    selector: '[data-tour="market-macro-content"]',
    titleKey: 'onboarding.tour.marketMacro.title',
    descKey: 'onboarding.tour.marketMacro.desc',
    placement: 'top',
    padding: 10,
    slowLoad: true,
  },
  {
    id: 'market-returns',
    path: '/market',
    clickSelector: '[data-tour="market-returns-tab"]',
    closeSelector: '[data-tour="market-overview-tab"]',
    selector: '[data-tour="market-returns-content"]',
    titleKey: 'onboarding.tour.marketReturns.title',
    descKey: 'onboarding.tour.marketReturns.desc',
    placement: 'top',
    padding: 10,
    slowLoad: true,
  },
  {
    id: 'market-search',
    path: '/market',
    selector: '[data-tour="market-search"]',
    titleKey: 'onboarding.tour.marketSearch.title',
    descKey: 'onboarding.tour.marketSearch.desc',
    placement: 'bottom',
    padding: 10,
  },
  {
    id: 'widget-edit',
    path: '/market',
    selector: '[data-tour="widget-edit"]',
    titleKey: 'onboarding.tour.widgetEdit.title',
    descKey: 'onboarding.tour.widgetEdit.desc',
    placement: 'bottom',
    padding: 8,
  },
  {
    id: 'detail-chart',
    path: '/stocks/THYAO.IS',
    selector: '[data-tour="detail-chart"]',
    titleKey: 'onboarding.tour.detailChart.title',
    descKey: 'onboarding.tour.detailChart.desc',
    placement: 'right',
    padding: 10,
    slowLoad: true,
  },
  {
    id: 'chart-lens',
    path: '/stocks/THYAO.IS',
    selector: '[data-tour="chart-lens"]',
    titleKey: 'onboarding.tour.chartLens.title',
    descKey: 'onboarding.tour.chartLens.desc',
    placement: 'bottom',
    padding: 10,
    optional: true,
    slowLoad: true,
  },
  {
    id: 'chart-drawing',
    path: '/stocks/THYAO.IS',
    selector: '[data-tour="chart-drawing-rail"]',
    titleKey: 'onboarding.tour.chartDrawing.title',
    descKey: 'onboarding.tour.chartDrawing.desc',
    placement: 'right',
    padding: 10,
    optional: true,
    slowLoad: true,
  },
  {
    id: 'fund-detail',
    path: '/funds/ACD',
    selector: '[data-tour="fund-profile"]',
    titleKey: 'onboarding.tour.fundDetail.title',
    descKey: 'onboarding.tour.fundDetail.desc',
    placement: 'auto',
    padding: 12,
    slowLoad: true,
  },
  {
    id: 'fund-allocation',
    path: '/funds/ACD',
    selector: '[data-tour="fund-allocation"]',
    titleKey: 'onboarding.tour.fundAllocation.title',
    descKey: 'onboarding.tour.fundAllocation.desc',
    placement: 'auto',
    padding: 10,
    slowLoad: true,
  },
  {
    id: 'bond-page',
    path: '/bonds',
    selector: '[data-tour="bond-page-main"]',
    titleKey: 'onboarding.tour.bondDetail.title',
    descKey: 'onboarding.tour.bondDetail.desc',
    placement: 'auto',
    padding: 12,
    slowLoad: true,
  },
  {
    id: 'bond-detail-card',
    clickSelector: '[data-tour="bond-list-first"]',
    selector: '[data-tour="bond-detail-card"]',
    titleKey: 'onboarding.tour.bondDetailPage.title',
    descKey: 'onboarding.tour.bondDetailPage.desc',
    placement: 'auto',
    padding: 12,
    slowLoad: true,
  },
  {
    id: 'bond-coupon',
    clickSelector: '[data-tour="bond-coupon-toggle"]',
    selector: '[data-tour="bond-coupon-chart"]',
    titleKey: 'onboarding.tour.bondCoupon.title',
    descKey: 'onboarding.tour.bondCoupon.desc',
    placement: 'top',
    padding: 10,
    slowLoad: true,
  },
  {
    id: 'news',
    path: '/news',
    selector: '[data-tour="news-list"]',
    titleKey: 'onboarding.tour.news.title',
    descKey: 'onboarding.tour.news.desc',
    placement: 'auto',
    padding: 12,
    optional: true,
    slowLoad: true,
  },
  {
    id: 'analytics-scenario',
    path: '/analytics',
    selector: '[data-tour="analytics-scenario"]',
    titleKey: 'onboarding.tour.analyticsScenario.title',
    descKey: 'onboarding.tour.analyticsScenario.desc',
    placement: 'auto',
    padding: 12,
    optional: true,
    slowLoad: true,
  },
  {
    id: 'analytics-beater',
    path: '/analytics',
    selector: '[data-tour="analytics-beater"]',
    titleKey: 'onboarding.tour.analyticsBeater.title',
    descKey: 'onboarding.tour.analyticsBeater.desc',
    placement: 'auto',
    padding: 12,
    optional: true,
    slowLoad: true,
  },
  {
    id: 'portfolio',
    path: '/portfolio',
    selector: ['[data-tour="portfolio-create"]', '[data-tour="position-search"]'],
    titleKey: 'onboarding.tour.portfolio.title',
    descKey: 'onboarding.tour.portfolio.desc',
    placement: 'top',
    padding: 10,
    slowLoad: true,
  },
  {
    id: 'portfolio-pdf',
    path: '/portfolio',
    selector: '[data-tour="portfolio-pdf"]',
    titleKey: 'onboarding.tour.portfolioPdf.title',
    descKey: 'onboarding.tour.portfolioPdf.desc',
    placement: 'bottom',
    padding: 8,
    slowLoad: true,
  },
  {
    id: 'watchlist',
    path: '/watch',
    selector: '[data-tour="watchlist-main"]',
    titleKey: 'onboarding.tour.watchlist.title',
    descKey: 'onboarding.tour.watchlist.desc',
    placement: 'auto',
    padding: 12,
    slowLoad: true,
  },
  {
    id: 'custom-lists',
    path: '/watch',
    selector: '[data-tour="watchlist-create"]',
    titleKey: 'onboarding.tour.customLists.title',
    descKey: 'onboarding.tour.customLists.desc',
    placement: 'auto',
    padding: 10,
    optional: true,
    slowLoad: true,
  },
  {
    id: 'notifications',
    path: '/market',
    clickSelector: '[data-tour="mobile-burger-open"]',
    closeSelector: '[data-tour="mobile-burger-close"]',
    selector: '[data-tour="notifications-bell"]',
    titleKey: 'onboarding.tour.notifications.title',
    descKey: 'onboarding.tour.notifications.desc',
    placement: 'right',
    padding: 8,
  },
  {
    id: 'settings',
    path: '/market',
    clickSelector: '[data-tour="settings-menu"]',
    closeSelector: ['[data-tour-close="settings"]', '[data-tour="mobile-burger-close"]'],
    selector: '[data-tour="settings-main"]',
    titleKey: 'onboarding.tour.settings.title',
    descKey: 'onboarding.tour.settings.desc',
    placement: 'left',
    padding: 12,
  },
  {
    id: 'profile',
    path: '/market',
    clickSelector: '[data-tour="profile-menu"]',
    closeSelector: ['[data-tour-close="profile"]', '[data-tour="mobile-burger-close"]'],
    selector: '[data-tour="profile-main"]',
    titleKey: 'onboarding.tour.profile.title',
    descKey: 'onboarding.tour.profile.desc',
    placement: 'left',
    padding: 12,
  },
  {
    id: 'summary',
    kind: 'summary',
    path: '/market',
    selector: null,
    titleKey: 'onboarding.tour.summary.title',
    descKey: 'onboarding.tour.summary.desc',
    placement: 'center',
    padding: 0,
  },
];

export default tourSteps;
