sonar.projectKey=finance-portal
sonar.projectName=Finance Portal
sonar.host.url=http://localhost:9000

sonar.sources=backend,finance-common/src/main,notification-backend/src/main,frontend/src
sonar.tests=backend,finance-common/src/test,notification-backend/src/test,frontend/src
sonar.test.inclusions=**/src/test/**,**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx
sonar.exclusions=**/dto/**,**/config/**,**/*MapperImpl.java,**/*Application.java,**/exception/**,**/migration/**,**/generated/**,**/node_modules/**,**/dist/**,**/build/**,**/target/**

sonar.java.binaries=**/target/classes
sonar.java.source=21

sonar.coverage.jacoco.xmlReportPaths=backend/finance-coverage/target/site/jacoco-aggregate/jacoco.xml,backend/finance-app/target/site/jacoco/jacoco.xml,finance-common/target/site/jacoco/jacoco.xml,notification-backend/target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/dto/**,**/config/**,**/*MapperImpl.java,**/*Application.java,**/exception/**,**/migration/**,**/generated/**,**/main.jsx,**/*.config.js

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
