spring:
  application:
    name: finance-notification
  config:
    import:
      - classpath:config/database.yaml
      - classpath:config/security.yaml
      - classpath:config/cache.yaml
      - classpath:config/kafka.yaml
      - classpath:config/mail.yaml
      - classpath:config/notification.yaml
      - classpath:config/market-hours.yaml
      - classpath:config/api.yaml
