export const TIMINGS = {
  RATE_LIMIT_THROTTLE_MS: 5000,
  TOAST_RATE_LIMIT_MIN_MS: 5000,
  TOAST_RATE_LIMIT_MAX_MS: 15000,
  TOAST_ERROR_DURATION_MS: 6000,
  TOAST_DEFAULT_DURATION_MS: 4000,
  SCROLL_SAVE_DEBOUNCE_MS: 200,
  SCROLL_MIN_HEIGHT_RELEASE_MS: 1500,
  POSITION_FORM_QUERY_STALE_MS: 60 * 60 * 1000,
};

export const LIMITS = {
  TOAST_MAX_VISIBLE: 5,
  RATE_LIMIT_THROTTLE_DEFAULT: 8,
};
