INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (87, 'COMMODITY', 'XAUTRY', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (89, 'COMMODITY', 'XAUTRYG', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (88, 'COMMODITY', 'XAGTRY', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (90, 'COMMODITY', 'XAGTRYG', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (94, 'COMMODITY', 'XPTTRY', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (95, 'COMMODITY', 'XPDTRY', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (91, 'COMMODITY', 'BZ=F', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (92, 'COMMODITY', 'ZW=F', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (93, 'COMMODITY', 'HG=F', true, now(), now()) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XAUTRY',  'Altın (Ons)',     NULL,           'PRECIOUS_METAL', 'GC=F', 87, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XAUTRYG', 'Altın (Gram)',    'Gram Altın',   'PRECIOUS_METAL', NULL,   89, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XAGTRY',  'Gümüş (Ons)',     NULL,           'PRECIOUS_METAL', 'SI=F', 88, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XAGTRYG', 'Gümüş (Gram)',    'Gram Gümüş',   'PRECIOUS_METAL', NULL,   90, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XPTTRY',  'Platin (Ons)',    NULL,           'PRECIOUS_METAL', 'PL=F', 94, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XPDTRY',  'Paladyum (Ons)',  NULL,           'PRECIOUS_METAL', 'PA=F', 95, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('BZ=F',    'Brent Petrol',    NULL,           'OTHER',          'BZ=F', 91, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('ZW=F',    'Buğday',          NULL,           'OTHER',          'ZW=F', 92, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('HG=F',    'Bakır',           NULL,           'OTHER',          'HG=F', 93, now(), now()) ON CONFLICT DO NOTHING;
