-- Commodity detail rows. The COMMODITY instruments themselves are seeded in V13 (alongside crypto —
-- the two types with no runtime discovery); commodities.asset_id -> instruments(id) created there.
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XAUTRY',  'Altın (Ons)',     NULL,           'PRECIOUS_METAL', 'GC=F', 87, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XAUTRYG', 'Altın (Gram)',    'Gram Altın',   'PRECIOUS_METAL', NULL,   89, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XAGTRY',  'Gümüş (Ons)',     NULL,           'PRECIOUS_METAL', 'SI=F', 88, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XAGTRYG', 'Gümüş (Gram)',    'Gram Gümüş',   'PRECIOUS_METAL', NULL,   90, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XPTTRY',  'Platin (Ons)',    NULL,           'PRECIOUS_METAL', 'PL=F', 94, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('XPDTRY',  'Paladyum (Ons)',  NULL,           'PRECIOUS_METAL', 'PA=F', 95, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('BZ=F',    'Brent Petrol',    NULL,           'OTHER',          'BZ=F', 91, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('ZW=F',    'Buğday',          NULL,           'OTHER',          'ZW=F', 92, now(), now()) ON CONFLICT DO NOTHING;
INSERT INTO public.commodities (commodity_code, name, commodity_name_tr, commodity_segment, yahoo_symbol, asset_id, created_at, updated_at) VALUES ('HG=F',    'Bakır',           NULL,           'OTHER',          'HG=F', 93, now(), now()) ON CONFLICT DO NOTHING;
