
CREATE TABLE IF NOT EXISTS public.notifications (
    id          bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.notifications_id_seq
        START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    ) NOT NULL,
    user_sub    character varying(64) NOT NULL,
    type        character varying(32) NOT NULL,
    title       character varying(255) NOT NULL,
    body        text NOT NULL,
    metadata    jsonb,
    read_at     timestamp without time zone,
    expires_at  timestamp without time zone,
    created_at  timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON public.notifications USING btree (user_sub, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread  ON public.notifications USING btree (user_sub, read_at) WHERE (read_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_notifications_expires      ON public.notifications USING btree (expires_at) WHERE (expires_at IS NOT NULL);

CREATE TABLE IF NOT EXISTS public.notification_preferences (
    user_sub                    character varying(64) NOT NULL,
    email_price_alerts          boolean DEFAULT true  NOT NULL,
    inapp_price_alerts          boolean DEFAULT true  NOT NULL,
    email_watchlist             boolean DEFAULT false NOT NULL,
    inapp_watchlist             boolean DEFAULT true  NOT NULL,
    email_system                boolean DEFAULT false NOT NULL,
    inapp_system                boolean DEFAULT true  NOT NULL,
    created_at                  timestamp without time zone DEFAULT now() NOT NULL,
    updated_at                  timestamp without time zone DEFAULT now() NOT NULL,
    email_enabled               boolean DEFAULT true  NOT NULL,
    email_market_opened         boolean DEFAULT false NOT NULL,
    inapp_market_opened         boolean DEFAULT true  NOT NULL,
    email_market_data_updated   boolean DEFAULT false NOT NULL,
    inapp_market_data_updated   boolean DEFAULT false NOT NULL,
    market_session_markets      character varying(96) DEFAULT 'STOCK,FOREX,FUND,COMMODITY,BOND,NEWS'::character varying NOT NULL,
    email_market_closed         boolean DEFAULT false NOT NULL,
    inapp_market_closed         boolean DEFAULT true  NOT NULL,
    email_news_published        boolean DEFAULT false NOT NULL,
    inapp_news_published        boolean DEFAULT true  NOT NULL,
    email_portfolio_updated     boolean DEFAULT false NOT NULL,
    inapp_portfolio_updated     boolean DEFAULT true  NOT NULL,
    version                     bigint  DEFAULT 0     NOT NULL,
    email_macro_indicators      boolean DEFAULT false NOT NULL,
    inapp_macro_indicators      boolean DEFAULT true  NOT NULL,
    CONSTRAINT notification_preferences_pkey PRIMARY KEY (user_sub)
);
