
CREATE TABLE IF NOT EXISTS public.price_alerts (
    id                bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.price_alerts_id_seq
        START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    ) NOT NULL,
    user_sub          character varying(64) NOT NULL,
    direction         character varying(20) NOT NULL,
    threshold         numeric(19,4) NOT NULL,
    currency          character varying(8) DEFAULT 'TRY'::character varying NOT NULL,
    reference_price   numeric(19,4),
    active            boolean DEFAULT true NOT NULL,
    triggered_at      timestamp without time zone,
    created_at        timestamp without time zone DEFAULT now() NOT NULL,
    tracked_asset_id  bigint NOT NULL,
    CONSTRAINT price_alerts_pkey PRIMARY KEY (id)
);

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_price_alerts_tracked_asset') THEN
        ALTER TABLE public.price_alerts
            ADD CONSTRAINT fk_price_alerts_tracked_asset FOREIGN KEY (tracked_asset_id)
            REFERENCES public.tracked_assets(id) ON DELETE CASCADE;
    END IF;
END $$;
