
CREATE TABLE IF NOT EXISTS public.watchlists (
    id          bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.watchlists_id_seq
        START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    ) NOT NULL,
    user_sub    character varying(64) NOT NULL,
    name        character varying(64) NOT NULL,
    is_default  boolean DEFAULT false NOT NULL,
    created_at  timestamp without time zone DEFAULT now() NOT NULL,
    updated_at  timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT watchlists_pkey PRIMARY KEY (id)
);

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_watchlists_user_name') THEN
        ALTER TABLE public.watchlists ADD CONSTRAINT uq_watchlists_user_name UNIQUE (user_sub, name);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.watchlist_items (
    id                bigint GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.watchlist_items_id_seq
        START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    ) NOT NULL,
    user_sub          character varying(64) NOT NULL,
    note              character varying(255),
    delta_threshold   numeric(7,4),
    last_seen_price   numeric(19,4),
    last_seen_at      timestamp without time zone,
    created_at        timestamp without time zone DEFAULT now() NOT NULL,
    watchlist_id      bigint NOT NULL,
    display_order     integer DEFAULT 0 NOT NULL,
    tracked_asset_id  bigint NOT NULL,
    CONSTRAINT watchlist_items_pkey PRIMARY KEY (id)
);

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_watchlist_items_list_tracked_asset') THEN
        ALTER TABLE public.watchlist_items ADD CONSTRAINT uq_watchlist_items_list_tracked_asset UNIQUE (watchlist_id, tracked_asset_id);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_watchlist_items_watchlist') THEN
        ALTER TABLE public.watchlist_items
            ADD CONSTRAINT fk_watchlist_items_watchlist FOREIGN KEY (watchlist_id)
            REFERENCES public.watchlists(id) ON DELETE CASCADE;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_watchlist_items_tracked_asset') THEN
        ALTER TABLE public.watchlist_items
            ADD CONSTRAINT fk_watchlist_items_tracked_asset FOREIGN KEY (tracked_asset_id)
            REFERENCES public.tracked_assets(id) ON DELETE CASCADE;
    END IF;
END $$;
