-- BIST indices (main: XU030/XU050/XU100; sub-sector: XBANK/XGIDA/XHOLD/XUSIN/XUTEK/...) — STOCK type,
-- index_asset=true. Seeded in Flyway (base, both modes) NOT the demo dump, because indices have no
-- runtime discovery: the İş Yatırım scraper finds tradable tickers, not index codes — so empty/prod
-- mode (make up, no demo dump) needs them here, same rationale as crypto+commodity in V13.
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (1, 'STOCK', 'XU030.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (2, 'STOCK', 'XU100.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (4, 'STOCK', 'XU050.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (64, 'STOCK', 'XBANK.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (65, 'STOCK', 'XUSIN.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (66, 'STOCK', 'XUTEK.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (67, 'STOCK', 'XGMYO.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (68, 'STOCK', 'XHOLD.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (69, 'STOCK', 'XULAS.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (70, 'STOCK', 'XKTUM.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (71, 'STOCK', 'XKTMT.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (72, 'STOCK', 'XTRZM.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (73, 'STOCK', 'XGIDA.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (74, 'STOCK', 'XMANA.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (13, 'STOCK', 'XU030.IS', NULL, 'MAIN_INDEX', 0, now(), now(), NULL, true, false, 1, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (14, 'STOCK', 'XU100.IS', NULL, 'MAIN_INDEX', 1, now(), now(), NULL, true, false, 2, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (16, 'STOCK', 'XU050.IS', NULL, 'MAIN_INDEX', 3, now(), now(), NULL, true, false, 4, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (76, 'STOCK', 'XBANK.IS', NULL, 'SECONDARY_INDEX', 100, now(), now(), NULL, true, true, 64, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (77, 'STOCK', 'XUSIN.IS', NULL, 'SECONDARY_INDEX', 101, now(), now(), NULL, true, true, 65, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (78, 'STOCK', 'XUTEK.IS', NULL, 'SECONDARY_INDEX', 102, now(), now(), NULL, true, true, 66, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (79, 'STOCK', 'XGMYO.IS', NULL, 'SECONDARY_INDEX', 103, now(), now(), NULL, true, true, 67, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (80, 'STOCK', 'XHOLD.IS', NULL, 'SECONDARY_INDEX', 104, now(), now(), NULL, true, true, 68, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (81, 'STOCK', 'XULAS.IS', NULL, 'SECONDARY_INDEX', 105, now(), now(), NULL, true, true, 69, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (82, 'STOCK', 'XKTUM.IS', NULL, 'SECONDARY_INDEX', 106, now(), now(), NULL, true, true, 70, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (83, 'STOCK', 'XKTMT.IS', NULL, 'SECONDARY_INDEX', 107, now(), now(), NULL, true, true, 71, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (84, 'STOCK', 'XTRZM.IS', NULL, 'SECONDARY_INDEX', 108, now(), now(), NULL, true, true, 72, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (85, 'STOCK', 'XGIDA.IS', NULL, 'SECONDARY_INDEX', 109, now(), now(), NULL, true, true, 73, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (86, 'STOCK', 'XMANA.IS', NULL, 'SECONDARY_INDEX', 110, now(), now(), NULL, true, true, 74, true) ON CONFLICT DO NOTHING;

-- Additional BIST sector indices (verified to have constituent pages); their member stocks and the
-- reverse 'index -> stocks' view populate at runtime via the scheduled enrichment, same as the set above.
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (96, 'STOCK', 'XUMAL.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (97, 'STOCK', 'XUHIZ.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (98, 'STOCK', 'XKMYA.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (99, 'STOCK', 'XMESY.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (100, 'STOCK', 'XMADN.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (101, 'STOCK', 'XTEKS.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (102, 'STOCK', 'XELKT.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (103, 'STOCK', 'XILTM.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (104, 'STOCK', 'XINSA.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (105, 'STOCK', 'XFINK.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (106, 'STOCK', 'XSGRT.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (107, 'STOCK', 'XSPOR.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (108, 'STOCK', 'XTCRT.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (109, 'STOCK', 'XBLSM.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (110, 'STOCK', 'XKAGT.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (111, 'STOCK', 'XTAST.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (112, 'STOCK', 'XKURY.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (113, 'STOCK', 'XKOBI.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (114, 'STOCK', 'XHARZ.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (115, 'STOCK', 'XBANA.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (100, 'STOCK', 'XUMAL.IS', NULL, 'SECONDARY_INDEX', 111, now(), now(), NULL, true, true, 96, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (101, 'STOCK', 'XUHIZ.IS', NULL, 'SECONDARY_INDEX', 112, now(), now(), NULL, true, true, 97, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (102, 'STOCK', 'XKMYA.IS', NULL, 'SECONDARY_INDEX', 113, now(), now(), NULL, true, true, 98, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (103, 'STOCK', 'XMESY.IS', NULL, 'SECONDARY_INDEX', 114, now(), now(), NULL, true, true, 99, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (104, 'STOCK', 'XMADN.IS', NULL, 'SECONDARY_INDEX', 115, now(), now(), NULL, true, true, 100, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (105, 'STOCK', 'XTEKS.IS', NULL, 'SECONDARY_INDEX', 116, now(), now(), NULL, true, true, 101, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (106, 'STOCK', 'XELKT.IS', NULL, 'SECONDARY_INDEX', 117, now(), now(), NULL, true, true, 102, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (107, 'STOCK', 'XILTM.IS', NULL, 'SECONDARY_INDEX', 118, now(), now(), NULL, true, true, 103, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (108, 'STOCK', 'XINSA.IS', NULL, 'SECONDARY_INDEX', 119, now(), now(), NULL, true, true, 104, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (109, 'STOCK', 'XFINK.IS', NULL, 'SECONDARY_INDEX', 120, now(), now(), NULL, true, true, 105, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (110, 'STOCK', 'XSGRT.IS', NULL, 'SECONDARY_INDEX', 121, now(), now(), NULL, true, true, 106, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (111, 'STOCK', 'XSPOR.IS', NULL, 'SECONDARY_INDEX', 122, now(), now(), NULL, true, true, 107, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (112, 'STOCK', 'XTCRT.IS', NULL, 'SECONDARY_INDEX', 123, now(), now(), NULL, true, true, 108, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (113, 'STOCK', 'XBLSM.IS', NULL, 'SECONDARY_INDEX', 124, now(), now(), NULL, true, true, 109, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (114, 'STOCK', 'XKAGT.IS', NULL, 'SECONDARY_INDEX', 125, now(), now(), NULL, true, true, 110, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (115, 'STOCK', 'XTAST.IS', NULL, 'SECONDARY_INDEX', 126, now(), now(), NULL, true, true, 111, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (116, 'STOCK', 'XKURY.IS', NULL, 'SECONDARY_INDEX', 127, now(), now(), NULL, true, true, 112, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (117, 'STOCK', 'XKOBI.IS', NULL, 'SECONDARY_INDEX', 128, now(), now(), NULL, true, true, 113, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (118, 'STOCK', 'XHARZ.IS', NULL, 'SECONDARY_INDEX', 129, now(), now(), NULL, true, true, 114, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (119, 'STOCK', 'XBANA.IS', NULL, 'SECONDARY_INDEX', 130, now(), now(), NULL, true, true, 115, true) ON CONFLICT DO NOTHING;

-- V13/V26 seed instruments AND tracked_assets with HARDCODED ids but never advance their sequences, so in
-- empty/prod mode (`make up`, no demo dump — the dump carries its own setval) the first runtime auto-discovery
-- insert (id DEFAULT nextval) collides with a seeded row on the primary key. Resync both sequences to their
-- current max id so runtime inserts continue past the seeded block. Idempotent; harmless in demo mode.
SELECT pg_catalog.setval('public.assets_id_seq',
    GREATEST((SELECT COALESCE(MAX(id), 0) FROM public.instruments), 1));
SELECT pg_catalog.setval('public.tracked_assets_id_seq',
    GREATEST((SELECT COALESCE(MAX(id), 0) FROM public.tracked_assets), 1));
