-- BIST indices (main: XU030/XU100/XU500; sub-sector: XBANK/XGIDA/XHOLD/XUSIN/XUTEK/...) — STOCK type,
-- index_asset=true. Seeded in Flyway (base, both modes) NOT the demo dump, because indices have no
-- runtime discovery: the İş Yatırım scraper finds tradable tickers, not index codes — so empty/prod
-- mode (make up, no demo dump) needs them here, same rationale as crypto+commodity in V13.
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (1, 'STOCK', 'XU030.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (2, 'STOCK', 'XU100.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (3, 'STOCK', 'XU500.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (64, 'STOCK', 'XBANK.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (65, 'STOCK', 'XUSIN.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (66, 'STOCK', 'XUTEK.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (67, 'STOCK', 'XGMYO.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (68, 'STOCK', 'XHOLD.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (69, 'STOCK', 'XULAS.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (70, 'STOCK', 'XKTUM.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (71, 'STOCK', 'XKTMT.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (72, 'STOCK', 'XTRZM.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (73, 'STOCK', 'XGIDA.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.instruments (id, instrument_type, asset_code, active, created_at, updated_at) VALUES (74, 'STOCK', 'XMANA.IS', true, now(), now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (13, 'STOCK', 'XU030.IS', NULL, 'MAIN_INDEX', 0, now(), now(), NULL, true, false, 1, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (14, 'STOCK', 'XU100.IS', NULL, 'MAIN_INDEX', 1, now(), now(), NULL, true, false, 2, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (15, 'STOCK', 'XU500.IS', NULL, 'MAIN_INDEX', 2, now(), now(), NULL, true, true, 3, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (76, 'STOCK', 'XBANK.IS', NULL, 'SECONDARY_INDEX', 100, now(), now(), NULL, true, true, 64, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (77, 'STOCK', 'XUSIN.IS', NULL, 'SECONDARY_INDEX', 101, now(), now(), NULL, true, true, 65, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (78, 'STOCK', 'XUTEK.IS', NULL, 'SECONDARY_INDEX', 102, now(), now(), NULL, true, true, 66, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (79, 'STOCK', 'XGMYO.IS', NULL, 'SECONDARY_INDEX', 103, now(), now(), NULL, true, true, 67, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (80, 'STOCK', 'XHOLD.IS', NULL, 'SECONDARY_INDEX', 104, now(), now(), NULL, true, true, 68, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (81, 'STOCK', 'XULAS.IS', NULL, 'SECONDARY_INDEX', 105, now(), now(), NULL, true, true, 69, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (82, 'STOCK', 'XKTUM.IS', NULL, 'SECONDARY_INDEX', 106, now(), now(), NULL, true, true, 70, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (83, 'STOCK', 'XKTMT.IS', NULL, 'SECONDARY_INDEX', 107, now(), now(), NULL, true, true, 71, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (84, 'STOCK', 'XTRZM.IS', NULL, 'SECONDARY_INDEX', 108, now(), now(), NULL, true, true, 72, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (85, 'STOCK', 'XGIDA.IS', NULL, 'SECONDARY_INDEX', 109, now(), now(), NULL, true, true, 73, true) ON CONFLICT DO NOTHING;
INSERT INTO public.tracked_assets (id, asset_type, asset_code, display_name, stock_segment, sort_order, created_at, updated_at, binance_symbol, index_asset, compare_only, asset_id, enabled) VALUES (86, 'STOCK', 'XMANA.IS', NULL, 'SECONDARY_INDEX', 110, now(), now(), NULL, true, true, 74, true) ON CONFLICT DO NOTHING;
