server {
    listen 9201;

    location / {
        proxy_pass https://opensearch:9200;
        proxy_ssl_verify off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        add_header X-Elastic-Product Elasticsearch always;
    }
}
