export const AUTH_REFRESH_INTERVAL_MS = 5000;
export const NOTIFICATION_RECONNECT_MS = 4000;
export const NOTIFICATION_HEARTBEAT_MS = 600000;
export const ONBOARDING_SUCCESS_HOLD_MS = 900;
export const REMOVAL_ANIMATION_MS = 200;
