app:
  timezone: Europe/Istanbul
  scale: 4

  http:
    connect-timeout-ms: 10000
    read-timeout-ms: 30000
    default-user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    evds-max-in-memory-size-mb: 10
    news-max-in-memory-size-mb: 5

  async:
    core-pool-size: 3
    max-pool-size: 5
    queue-capacity: 25
