spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 60000ms

app:
  cache:
    redis-default-ttl-hours: 24
  fx:
    cache-ttl-minutes: 60
    cache-max-entries: 1000
    lookback-days: 14
