app:
  tefas-api-path: /api/funds/fonGnlBlgSiraliGetir
  tefas-base-url: https://www.tefas.gov.tr
  tefas-session-path: /tr

  api:
    coingecko:
      base-url: https://api.coingecko.com/api/v3
      user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      api-key-header: x-cg-demo-api-key
      markets-path: /coins/markets
    evds:
      base-url: https://evds3.tcmb.gov.tr/igmevdsms-dis
      user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      api-key-header: key
      serie-list-path: /serieList/type=json&code=
      series-path: /series=
    yahoo:
      base-url: https://query1.finance.yahoo.com/v8/finance/chart/
      user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      chart-path: ""
    binance:
      base-url: https://api.binance.com
      klines-path: /api/v3/klines

  market:
    viop:
      base-url: https://www.isyatirim.com.tr
      contract-list-page-path: /tr-tr/urunler/Sayfalar/Islem-Goren-Kontratlar.aspx
      viop-analysis-page-path: /tr-tr/analiz/Sayfalar/viop.aspx
      vadeli-metadata-path: /_layouts/15/Isyatirim.Website/Common/Data.aspx/VadeliIslemler
      opsiyon-metadata-path: /_layouts/15/Isyatirim.Website/Common/Data.aspx/OpsiyonSozlesmeleri
      one-endeks-path: /_layouts/15/Isyatirim.Website/Common/Data.aspx/OneEndeks
      chart-data-path: /_Layouts/15/IsYatirim.Website/Common/ChartData.aspx/IndexHistoricalAll
      user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.2 Safari/605.1.15"
      session-ttl: 30m
      request-timeout: 20s
