spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        '[enable.idempotence]': true
      retries: 5

app:
  kafka:
    topics:
      market-updated: market.updated
      news-published: news.published
      portfolio-updated: portfolio.updated
      macro-indicators-updated: macro.indicators.updated
      user-email-change-code: user.email-change.code-requested
      mail-dispatch: mail.dispatch
    admin:
      default-partitions: 3
      low-volume-partitions: 1
      default-replicas: 1
      default-retention-ms: 86400000
