notification:
  market-hours:
    markets:
      STOCK:
        open: '10:00'
        close: '18:00'
        trading-days: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY]
        zone: Europe/Istanbul
      FOREX:
        open: '09:00'
        close: '17:00'
        trading-days: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY]
        zone: Europe/Istanbul
      FUND:
        open: '09:30'
        close: '13:30'
        trading-days: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY]
        zone: Europe/Istanbul
      BOND:
        open: '09:30'
        close: '17:30'
        trading-days: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY]
        zone: Europe/Istanbul
      COMMODITY:
        open: '01:00'
        close: '23:59'
        trading-days: [SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY]
        zone: Europe/Istanbul
      CRYPTO:
        open: '00:00'
        close: '00:00'
        trading-days: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY]
        zone: Europe/Istanbul
      VIOP:
        open: '09:30'
        close: '18:15'
        trading-days: [MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY]
        zone: Europe/Istanbul
