notification:
    keywords:
      sabah:
        - morning
        - sabah
      öğlen:
        - afternoon
        - midday
        - noon
        - öğle
        - ogle
      akşam:
        - evening
        - aksam
        - akşam
      günlük:
        - daily
        - full
