notification:
    keywords:
      morning:
        - morning
        - sabah
      noon:
        - afternoon
        - midday
        - noon
        - öğle
        - ogle
        - öğlen
        - oglen
      evening:
        - evening
        - aksam
        - akşam
      daily:
        - daily
        - full
